[tool.mypy]
python_version = "3.11"
strict = true
warn_unreachable = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "gradio_client",
    "mido",
    "midiutil",
    "torch",
    "transformers",
]
ignore_missing_imports = true
